version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_webhook_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: webhook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

volumes:
  postgres_data:
